---

all:
  hosts:
    dbserver:
      ansible_connection: ssh
      ansible_ssh_user: ec2-user
      #ansible_ssh_private_key_file: 
      #ansible_host: dbserver

      #oracle_url_base: http://image.server/oracle/
      oracle_release: 19c
      oracle_install_type: restart      
  children:
    oracle:
      hosts:
        dbserver:
      vars:
  vars:
